language: python # => 1

    python: # => 2

      - "2.6"

      - "2.7"

     services:
        - mysql

    env: # => 4

       - DJANGO_VERSION=1.10.8 DB=mysql
    
    before_install:
        - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
    
    install: # => 5

      - pip install -r requirements.txt
      - pip install -q Django==1.10.8
      - python setup.py -q install

    
    script: # => 7

      - python manage.py test
      
    notifications:
    email:
        - ankit.pahuja05@gmail.com
